[package]
name = "bitcoin-mock-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.0"
secp256k1 = "0.29.0"
serde = { version = "1.0", default-features = false }
serde_json = "1.0.108"
bitcoincore-rpc = { git = "https://github.com/rust-bitcoin/rust-bitcoincore-rpc.git" }
bitcoin-simulator = { git = "https://github.com/chainwayxyz/bitcoin-simulator" }
