name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Compile code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile in debug mode
      run: cargo build --verbose --workspace --all-targets --all-features
    - name: Compile in release mode
      run: cargo build --verbose --workspace --all-targets --all-features --release
